services:
  server-db:
    restart: unless-stopped
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    ports:
      - 5435:5432
    networks:
      - net

networks:
  net: